# -*- coding: utf-8 -*-
"""WEEK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOxBI2x1Mw9eA4t1eeid-kxh-sRr2bVt

# **list**

Creation of List
"""

lis1=[1,2,3,6,8,20]
print(lis1)
lis2=["abc","def","hyd","delhi","Mumbai"]
print(lis2)
lis3=["a","Main Flow",True,15,22.5,15+6j]
print(lis3)

"""Adding elements to a list"""

lis=[]
#Adding elements at end
lis.append("Data")
lis.append("Science")
lis.append("Python")
print(lis)
#Adding elements at particular position
lis.insert(2,"with")
print(lis)

"""Removing elements to a list"""

print(lis)
#Removing the last element
lis.pop()
print(lis)
#Removing the element at particular index
lis.pop(1)
print(lis)
lis.append("Main")
lis.append("Flow")
print(lis)
#Removing the particular element from list
lis.remove("Data")
print(lis)

"""Modifing the list"""

lis=["Data","Science","with","python"]
print(lis)
#Replacing the element at particular index
lis[2]="using"
print(lis)
lis=[1,2,3,4,5,6,7]
print(lis)
#Replacing the part of list
lis[2:5]=[5,4]
print(lis)

"""# **Dictonary**

Creating dictonary
"""

dic={"CSE":60,"ECE":60,"EEE":60,"PHARMACY":100}
print(dic)

"""Adding elements"""

print(dic)
dic["Petroleum"]=80
print(dic)
#Keys in a dictonary
print(dic.keys())
#values in a dictonary
print(dic.values())

"""Removing elements"""

print(dic)
del dic["CSE"]
print(dic)

"""Modifing elements"""

print(dic)
dic["ECE"]=80
print(dic)
#Accessing the Key not in a dictonary
print(dic["CSE"])

"""# **Set**

Creating a Set
"""

sets={"MAIN","FLOW","SERVICES","TECHNOLIGIES","MAIN"}
print(sets)

"""Adding an elements"""

sets=set()
sets.add("CSE")
sets.add("ECE")
sets.add("CSIT")
print(sets)

"""Removing the elements"""

print(sets)
sets.discard("CSE")
print(sets)