# -*- coding: utf-8 -*-
"""Week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IyO8vbo6Y-ZfQwrC-rtTaBy7WogRrQ_s

# **Data Cleaning and Preprocessing**
"""

#importing the libraries
import pandas as pd
import numpy as np
#loading the csv file
data=pd.read_csv("01.Data Cleaning and Preprocessing.csv")

#Viewing the data
data.head()

k=data.shape
print("No of features:",k[1])
print("No of objects:",k[0])

data.drop_duplicates(inplace=True)
#After dropping the duplicate rows
k=data.shape
print("No of features:",k[1])
print("No of objects:",k[0])

#satistical description of the data
data.describe()

#Null values in the data
data_null=data.isnull().sum()
print(data_null)

#Modifing the null values with zero
data_modified1=data.fillna(0)
data_null=data_modified1.isnull().sum()
print(data_null)

#Modifing the null values using forward filling methood
data_modified=data.fillna(method="pad")
data_null=data_modified.isnull().sum()
print(data_null)

#Modifing the null values using backward filling methood
data_modified=data.fillna(method="bfill")
data_null=data_modified.isnull().sum()
print(data_null)

#dropping the rows containing null values
data_cleaned=data.dropna()
k=data_cleaned.shape
#After dropping the rows with null values
print("No of features:",k[1])
print("No of objects:",k[0])

#data features
data.columns

#droping a particular feature
data.drop(["BlowFlow"],inplace=True,axis=1)
print(data.columns)

#data types of a features
data_modified1.dtypes

#Explicit conversion of data to numeric
data_modified1 = data_modified1.apply(pd.to_numeric, errors='coerce')
#calculation of Inter Quartile range
Q1 = data_modified1.quantile(0.25)
Q3 = data_modified1.quantile(0.75)
IQR = Q3 - Q1
print(IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
#dropping the outliers based on inter Quartile Range
filtered_data = data_modified1[~((data_modified1 < lower_bound) | (data_modified1 > upper_bound)).any(axis=1)]
print(filtered_data.shape)

#Statistical description of processed data
data.describe()